Translations update from Hosted Weblate
mediathekview/zapp pull request #326
Opened 2022-10-22 23:55 UTC by weblate

Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Zapp/app](https://hosted.weblate.org/projects/zapp/app/).

It also includes following components:

* [Zapp/fastlane](https://hosted.weblate.org/projects/zapp/fastlane/)

Current translation status:

![Weblate translation status](https://hosted.weblate.org/widgets/zapp/-/app/horizontal-auto.svg)

2022-11-21 13:37 UTC, eUgEntOptIc44 commented
Weblate has unfortunately **blocked** further contributions to the translations of zapp for the time being. As of writing this PR is waiting for a review for a few weeks and weblate's internal timeout for a possible merge has blocked the project.

2022-12-23 16:07 UTC, cemrich requested changes

2022-12-23 16:07 UTC, cemrich commented on fastlane/metadata/android/en/changelogs/52.txt
> +* Fixed downloads not working
F-Droid falls back to en-US for fastlane metadata. So any translation tool needs to support this. "en" is most likely not going to work in this place.

2022-12-23 16:07 UTC, cemrich commented on app/src/main/res/values-en/strings.xml
> +<?xml version="1.0" encoding="utf-8"?>
I am sorry I created conflicts in this file during refactoring / development :(

2022-12-23 16:11 UTC, cemrich commented
Sorry, for my very late response! 

The work of the translators is amazing! But I need to have a very solid setup, so nothing breaks during development and - most importantly - release. My main concern right now is the fastlane `en` directory. In order for it to work as a F-Droid backup it [need to be](https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots/#fastlane-struktur) an `en-US` directory. Can this be achieved with weblate?

I'll continue reviewing all weblate changes and try to put them all on the [feature/weblate](https://github.com/mediathekview/zapp/tree/feature/weblate) branch.

2023-12-22 13:56 UTC, cemrich commented
I am verry, verry sorry it took me so long to look into this. I repaired the existing transifex integration which now can be used once again.

I your are still interested, you are free to join the translation team at https://explore.transifex.com/none-581/zapp-android-app/ I created a fresh French translation there.

2023-12-22 13:56 UTC, closed without merging